In [177]:
# Imports
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from IPython.display import display
from sklearn import metrics

In [178]:
df_raw = pd.read_csv('training_set_features.csv', low_memory=False,)
dfh1 = pd.read_csv('training_set_labels.csv')
testing_df_raw = pd.read_csv('test_set_features.csv', low_memory=False,)

In [179]:
df_raw['h1n1_vaccine'] = dfh1['h1n1_vaccine']
df_raw.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,h1n1_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0

In [180]:
df_raw = df_raw.drop(['employment_industry', 'employment_occupation', 'hhs_geo_region'], axis = 1)
testing_df_raw = testing_df_raw.drop(['employment_industry', 'employment_occupation', 'hhs_geo_region'], axis = 1)
df_raw.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa,household_adults,household_children,h1n1_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,Non-MSA,0.0,0.0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,White,Male,Below Poverty,Not Married,Rent,Employed,"MSA, Not Principle City",0.0,0.0,0
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,"MSA, Not Principle City",2.0,0.0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,"MSA, Principle City",0.0,0.0,0
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,"MSA, Not Principle City",1.0,0.0,0

In [181]:
df_raw.dtypes
testing_df_raw.dtypes

respondent_id                    int64
h1n1_concern                   float64
h1n1_knowledge                 float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_h1n1               float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_h1n1_vacc_effective    float64
opinion_h1n1_risk              float64
opinion_h1n1_sick_from_vacc    float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                       object
education                       object
race                            object
sex                             object
income_poverty                  object
marital_status                  object
rent_or_own                     object
employment_status               object
census_msa                      object
household_adults               float64
household_children             float64
dtype: object

In [182]:
obj_df = df_raw.select_dtypes(include=['object']).copy()
obj_df

testing_obj_df = testing_df_raw.select_dtypes(include=['object']).copy()
testing_obj_df

,age_group,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,census_msa
0,35 - 44 Years,College Graduate,Hispanic,Female,"> $75,000",Not Married,Rent,Employed,"MSA, Not Principle City"
1,18 - 34 Years,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,Non-MSA
2,55 - 64 Years,College Graduate,White,Male,"> $75,000",Married,Own,Employed,Non-MSA
3,65+ Years,12 Years,White,Female,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,"MSA, Not Principle City"
4,35 - 44 Years,12 Years,Black,Female,"<= $75,000, Above Poverty",Not Married,Own,Employed,Non-MSA
...,...,...,...,...,...,...,...,...,...
26703,35 - 44 Years,NaN,White,Female,NaN,NaN,NaN,NaN,"MSA, Principle City"
26704,18 - 34 Years,12 Years,White,Male,Below Poverty,Married,Rent,Employed,Non-MSA
26705,18 - 34 Years,Some College,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,"MSA, Not Principle City"
26706,55 - 64 Years,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,"MSA, Not Principle City"
26707,45 - 54 Years,College Graduate,White,Female,NaN,Not Married,Rent,Employed,"MSA, Principle City"

In [183]:
# Columns with blanks - education, income, marital, rent, employment, household_adults, household_children
obj_df['income_poverty'].isnull().sum()
testing_obj_df['income_poverty'].isnull().sum()
# obj_df[obj_df.isnull().any(axis=1)]

4497

In [190]:
# def fillblanks(column, number):
#     obj_df[column] = obj_df[column].fillna(number)
#     print(obj_df[column].isnull().sum())

def fillblanks(columnname, fillvalue, dataframe):
    dataframe[columnname] = dataframe[columnname].fillna(fillvalue)
    print(dataframe[columnname].isnull().sum())
    
fillblanks('income_poverty', 3, df_raw)
fillblanks('education', 4, df_raw)
fillblanks('marital_status', 2, df_raw)
fillblanks('rent_or_own', 2, df_raw)
fillblanks('employment_status', 3, df_raw)
# fillblanks('census_msa', 2, df_raw)
fillblanks('h1n1_concern', 4, df_raw)
fillblanks('h1n1_knowledge', 3, df_raw)
fillblanks('behavioral_antiviral_meds', 2, df_raw)
fillblanks('behavioral_avoidance', 2, df_raw)
fillblanks('behavioral_face_mask', 2, df_raw)
fillblanks('behavioral_wash_hands', 2, df_raw)
fillblanks('behavioral_large_gatherings', 2, df_raw)
fillblanks('behavioral_outside_home', 2, df_raw)
fillblanks('behavioral_touch_face', 2, df_raw)
fillblanks('doctor_recc_h1n1', 2, df_raw)
fillblanks('doctor_recc_seasonal', 2, df_raw)
fillblanks('chronic_med_condition', 2, df_raw)
fillblanks('child_under_6_months', 2, df_raw)
fillblanks('health_worker', 2, df_raw)
fillblanks('health_insurance', 2, df_raw)
fillblanks('opinion_h1n1_vacc_effective', 6, df_raw)
fillblanks('opinion_h1n1_risk', 6, df_raw)
fillblanks('opinion_h1n1_sick_from_vacc', 6, df_raw)
fillblanks('opinion_seas_vacc_effective', 6, df_raw)
fillblanks('opinion_seas_risk', 6, df_raw)
fillblanks('opinion_seas_sick_from_vacc', 6, df_raw)
fillblanks('household_adults', 4, df_raw)
fillblanks('household_children', 4, df_raw)

fillblanks('income_poverty', 3, testing_df_raw)
fillblanks('education', 4, testing_df_raw)
fillblanks('marital_status', 2, testing_df_raw)
fillblanks('rent_or_own', 2, testing_df_raw)
fillblanks('employment_status', 3, testing_df_raw)
fillblanks('census_msa', 2, testing_df_raw)
fillblanks('h1n1_concern', 4, testing_df_raw)
fillblanks('h1n1_knowledge', 3, testing_df_raw)
fillblanks('behavioral_antiviral_meds', 2, testing_df_raw)
fillblanks('behavioral_avoidance', 2, testing_df_raw)
fillblanks('behavioral_face_mask', 2, testing_df_raw)
fillblanks('behavioral_wash_hands', 2, testing_df_raw)
fillblanks('behavioral_large_gatherings', 2, testing_df_raw)
fillblanks('behavioral_outside_home', 2, testing_df_raw)
fillblanks('behavioral_touch_face', 2, testing_df_raw)
fillblanks('doctor_recc_h1n1', 2, testing_df_raw)
fillblanks('doctor_recc_seasonal', 2, testing_df_raw)
fillblanks('chronic_med_condition', 2, testing_df_raw)
fillblanks('child_under_6_months', 2, testing_df_raw)
fillblanks('health_worker', 2, testing_df_raw)
fillblanks('health_insurance', 2, testing_df_raw)
fillblanks('opinion_h1n1_vacc_effective', 6, testing_df_raw)
fillblanks('opinion_h1n1_risk', 6, testing_df_raw)
fillblanks('opinion_h1n1_sick_from_vacc', 6, testing_df_raw)
fillblanks('opinion_seas_vacc_effective', 6, testing_df_raw)
fillblanks('opinion_seas_risk', 6, testing_df_raw)
fillblanks('opinion_seas_sick_from_vacc', 6, testing_df_raw)
fillblanks('household_adults', 4, testing_df_raw)
fillblanks('household_children', 4, testing_df_raw)

# obj_df['income_poverty'] = obj_df['income_poverty'].fillna('4')
# obj_df['income_poverty'].isnull().sum()

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [193]:
pd.set_option('display.max_rows', 100)
# def makeCategories(columnname, newcolumnname):
#     obj_df[columnname] = obj_df[columnname].astype('category')
#     obj_df[newcolumnname] = obj_df[columnname].cat.codes

def makeCategories(columnname, newcolumnname, dataframe):
    dataframe[columnname] = dataframe[columnname].astype('category')
    dataframe[newcolumnname] = dataframe[columnname].cat.codes
# def makeCategories(columnname, newcolumnname):
#     df_raw[columnname] = df_raw[columnname].astype('category')
#     df_raw[newcolumnname] = df_raw[columnname].cat.codes
    
makeCategories('income_poverty', 'income_poverty_cat', df_raw)
makeCategories('education', 'education_cat', df_raw)
makeCategories('marital_status', 'marital_status_cat', df_raw)
makeCategories('rent_or_own', 'rent_or_own_cat', df_raw)
makeCategories('employment_status', 'employment_status_cat', df_raw)
makeCategories('census_msa', 'census_msa_cat', df_raw)
makeCategories('age_group', 'age_group_cat', df_raw)
makeCategories('race', 'race_cat', df_raw)
makeCategories('sex', 'sex_cat', df_raw)
print(df_raw)

makeCategories('income_poverty', 'income_poverty_cat', testing_df_raw)
makeCategories('education', 'education_cat', testing_df_raw)
makeCategories('marital_status', 'marital_status_cat', testing_df_raw)
makeCategories('rent_or_own', 'rent_or_own_cat', testing_df_raw)
makeCategories('employment_status', 'employment_status_cat', testing_df_raw)
makeCategories('census_msa', 'census_msa_cat', testing_df_raw)
makeCategories('age_group', 'age_group_cat', testing_df_raw)
makeCategories('race', 'race_cat', testing_df_raw)
makeCategories('sex', 'sex_cat', testing_df_raw)
print(testing_df_raw)

# obj_df["income_poverty"] = obj_df["income_poverty"].astype('category')
# obj_df["income_poverty_cat"] = obj_df["income_poverty"].cat.codes

       respondent_id  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0                  0           1.0             0.0                        0.0
1                  1           3.0             2.0                        0.0
2                  2           1.0             1.0                        0.0
3                  3           1.0             1.0                        0.0
4                  4           2.0             1.0                        0.0
...              ...           ...             ...                        ...
26702          26702           2.0             0.0                        0.0
26703          26703           1.0             2.0                        0.0
26704          26704           2.0             2.0                        0.0
26705          26705           1.0             1.0                        0.0
26706          26706           0.0             0.0                        0.0

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0
1                       1.0                   0.0                    1.0
2                       1.0                   0.0                    0.0
3                       1.0                   0.0                    1.0
4                       1.0                   0.0                    1.0
...                     ...                   ...                    ...
26702                   1.0                   0.0                    0.0
26703                   1.0                   0.0                    1.0
26704                   1.0                   1.0                    1.0
26705                   0.0                   0.0                    0.0
26706                   1.0                   0.0                    0.0

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0
1                              0.0                      1.0
2                              0.0                      0.0
3                              1.0                      0.0
4                              1.0                      0.0
...                            ...                      ...
26702                          0.0                      1.0
26703                          0.0                      0.0
26704                          1.0                      0.0
26705                          0.0                      0.0
26706                          0.0                      0.0

       behavioral_touch_face  ...  h1n1_vaccine  income_poverty_cat  \
0                        1.0  ...             0                   3
1                        1.0  ...             0                   3
2                        0.0  ...             0                   1
3                        0.0  ...             0                   3
4                        1.0  ...             0                   1
...                      ...  ...           ...                 ...
26702                    0.0  ...             0                   1
26703                    0.0  ...             0                   1
26704                    1.0  ...             0                   0
26705                    2.0  ...             0                   1
26706                    0.0  ...             0                   1

       education_cat  marital_status_cat  rent_or_own_cat  \
0                  2                   2                1
1                  1                   2                2
2                  3                   2                1
3                  1                   2                2
4                  4                   1                1
...              ...                 ...              ...
26702              4                   2                1
26703              3                   2                2
26704              4                   2                1
26705              4                   1                2
26706              4                   1                1

       employment_status_cat  census_msa_cat  age_group_cat  race_cat  sex_cat
0                          2               2              3         3        0
1                          1               0              1         3        1
2                          1               0              0         3        1
3                          2               1              4         3        0
4                          1               0              2         3        0
...                      ...             ...            ...       ...      ...
26702                      2               2              4         3        0
26703                      1               1              0         3        1
26704                      0               0              3         3        0
26705                      1               2              0         1        0
26706                      2               1              4         3        1

[26707 rows x 43 columns]
       respondent_id  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0              26707           2.0             2.0                        0.0
1              26708           1.0             1.0                        0.0
2              26709           2.0             2.0                        0.0
3              26710           1.0             1.0                        0.0
4              26711           3.0             1.0                        1.0
...              ...           ...             ...                        ...
26703          53410           1.0             1.0                        0.0
26704          53411           3.0             1.0                        0.0
26705          53412           0.0             1.0                        0.0
26706          53413           3.0             1.0                        0.0
26707          53414           2.0             1.0                        0.0

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       1.0                   0.0                    1.0
1                       0.0                   0.0                    0.0
2                       0.0                   1.0                    1.0
3                       0.0                   0.0                    0.0
4                       1.0                   0.0                    1.0
...                     ...                   ...                    ...
26703                   1.0                   0.0                    1.0
26704                   1.0                   0.0                    1.0
26705                   0.0                   0.0                    0.0
26706                   1.0                   0.0                    1.0
26707                   0.0                   0.0                    1.0

       behavioral_large_gatherings  behavioral_outside_home  \
0                              1.0                      0.0
1                              0.0                      0.0
2                              1.0                      1.0
3                              0.0                      0.0
4                              1.0                      1.0
...                            ...                      ...
26703                          0.0                      0.0
26704                          1.0                      1.0
26705                          0.0                      0.0
26706                          0.0                      1.0
26707                          0.0                      0.0

       behavioral_touch_face  ...  household_children  income_poverty_cat  \
0                        1.0  ...                 0.0                   2
1                        0.0  ...                 0.0                   3
2                        1.0  ...                 0.0                   2
3                        0.0  ...                 0.0                   1
4                        1.0  ...                 1.0                   1
...                      ...  ...                 ...                 ...
26703                    1.0  ...                 1.0                   0
26704                    1.0  ...                 3.0                   3
26705                    0.0  ...                 0.0                   3
26706                    0.0  ...                 0.0                   1
26707                    1.0  ...                 0.0                   0

       education_cat  marital_status_cat  rent_or_own_cat  \
0                  3                   2                2
1                  1                   2                2
2                  3                   1                1
3                  1                   1                1
4                  1                   2                1
...              ...                 ...              ...
26703              0                   0                0
26704              1                   1                2
26705              4                   2                2
26706              4                   1                1
26707              3                   2                2

       employment_status_cat  census_msa_cat  age_group_cat  race_cat  sex_cat
0                          1               0              1         1        0
1                          1               2              0         3        1
2                          1               2              3         3        1
3                          2               0              4         3        0
4                          1               2              1         0        0
...                      ...             ...            ...       ...      ...
26703                      0               1              1         3        0
26704                      1               2              0         3        1
26705                      2               0              0         3        0
26706                      2               0              3         3        0
26707                      1               1              2         3        0

[26708 rows x 42 columns]

In [194]:
# print(df_raw)
modelready = df_raw.drop(['income_poverty', 'education', 'marital_status', 'rent_or_own', 'employment_status', 'census_msa', 'age_group', 'race', 'sex'], axis = 1)
testingmodelready = testing_df_raw.drop(['income_poverty', 'education', 'marital_status', 'rent_or_own', 'employment_status', 'census_msa', 'age_group', 'race', 'sex'], axis = 1)

# modelready2 = obj_df.drop(['income_poverty', 'education', 'marital_status', 'rent_or_own', 'employment_status', 'census_msa', 'age_group', 'race', 'sex'], axis = 1)
# modelready = pd.concat([modelready1, modelready2], axis=1)
print(modelready)

       respondent_id  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0                  0           1.0             0.0                        0.0
1                  1           3.0             2.0                        0.0
2                  2           1.0             1.0                        0.0
3                  3           1.0             1.0                        0.0
4                  4           2.0             1.0                        0.0
...              ...           ...             ...                        ...
26702          26702           2.0             0.0                        0.0
26703          26703           1.0             2.0                        0.0
26704          26704           2.0             2.0                        0.0
26705          26705           1.0             1.0                        0.0
26706          26706           0.0             0.0                        0.0

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0
1                       1.0                   0.0                    1.0
2                       1.0                   0.0                    0.0
3                       1.0                   0.0                    1.0
4                       1.0                   0.0                    1.0
...                     ...                   ...                    ...
26702                   1.0                   0.0                    0.0
26703                   1.0                   0.0                    1.0
26704                   1.0                   1.0                    1.0
26705                   0.0                   0.0                    0.0
26706                   1.0                   0.0                    0.0

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0
1                              0.0                      1.0
2                              0.0                      0.0
3                              1.0                      0.0
4                              1.0                      0.0
...                            ...                      ...
26702                          0.0                      1.0
26703                          0.0                      0.0
26704                          1.0                      0.0
26705                          0.0                      0.0
26706                          0.0                      0.0

       behavioral_touch_face  ...  h1n1_vaccine  income_poverty_cat  \
0                        1.0  ...             0                   3
1                        1.0  ...             0                   3
2                        0.0  ...             0                   1
3                        0.0  ...             0                   3
4                        1.0  ...             0                   1
...                      ...  ...           ...                 ...
26702                    0.0  ...             0                   1
26703                    0.0  ...             0                   1
26704                    1.0  ...             0                   0
26705                    2.0  ...             0                   1
26706                    0.0  ...             0                   1

       education_cat  marital_status_cat  rent_or_own_cat  \
0                  2                   2                1
1                  1                   2                2
2                  3                   2                1
3                  1                   2                2
4                  4                   1                1
...              ...                 ...              ...
26702              4                   2                1
26703              3                   2                2
26704              4                   2                1
26705              4                   1                2
26706              4                   1                1

       employment_status_cat  census_msa_cat  age_group_cat  race_cat  sex_cat
0                          2               2              3         3        0
1                          1               0              1         3        1
2                          1               0              0         3        1
3                          2               1              4         3        0
4                          1               0              2         3        0
...                      ...             ...            ...       ...      ...
26702                      2               2              4         3        0
26703                      1               1              0         3        1
26704                      0               0              3         3        0
26705                      1               2              0         1        0
26706                      2               1              4         3        1

[26707 rows x 34 columns]

In [187]:
unique_values =  pd.unique(modelready['census_msa_cat'])
print(unique_values)

[2 0 1]

In [196]:
m = RandomForestClassifier(n_jobs=-1)
m.fit(modelready.drop('h1n1_vaccine', axis=1), modelready.h1n1_vaccine)
m.score(modelready.drop('h1n1_vaccine', axis=1), modelready.h1n1_vaccine)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.9855094170067773

In [202]:
# m.predict(testingmodelready)
results = pd.DataFrame(data=m.predict(testingmodelready))
print(results)

       0
0      0
1      0
2      0
3      0
4      0
...   ..
26703  1
26704  0
26705  0
26706  0
26707  0

[26708 rows x 1 columns]

In [204]:
results.to_csv('results.csv')